### ISSUE TITLE
Error while loading the middleware

### ISSUE THREAD

**Issue by fmatray** [lambdalisue/django-author#18]
Hello,
According to the post below, the middleware needs a 2 more functions to start correctly.
https://stackoverflow.com/questions/42232606/django-exception-middleware-typeerror-object-takes-no-parameters
see also : https://docs.djangoproject.com/en/1.10/topics/http/middleware/#writing-your-own-middleware

Else I get : 
    mw_instance = middleware(handler)
TypeError: object() takes no parameters

in middle, just add :
```
class AuthorDefaultBackendMiddleware(object):
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        return self.get_response(request)
```

Thanks for your project :-)

**Comment by PetrDlouhy** [comment]
@fmatray Could you please make this to a Pull request?
