### ISSUE TITLE
Give a MAINTAINER role of PyPI to collaborator

### ISSUE THREAD

**Issue by lambdalisue** [lambdalisue/django-author#7]
@PetrDlouhy 
Today I noticed that I can give a maintainer role to others in PyPI. So let me know your account and I'll give you a maintainer role then you can update PyPI version I guess ;-)

**Comment by PetrDlouhy** [comment]
Thanks, my username is "petr.dlouhy"

**Comment by lambdalisue** [comment]
Done. Now you should be able to define the version and update the PyPI version. Let me know if there is a problem ;-)

**Comment by PetrDlouhy** [comment]
Nice. I uploaded the Django 1.9 compatible version.

**Comment by lambdalisue** [comment]
Sounds good. Thanks ;-)
